---
title: "Quiz1_207368846"
author: "David"
format: html
editor: visual
---

## Before I start the Quiz!

I paste the Quiz files from the moodle into a specific directory.

``` bash
cd ~/ADS_Q1
```

## Part 1

#### Question 1

What is one of the purposes of the YAML header in a Quarto document?

1.  To store the document\'s contents.

2.  To specify the document\'s format.

3.  To add comments to the document.

4.  To include images in the document.

#### Answer 1: 

2.  To specify the document\'s format.

#### Question 2

What is the purpose of a commit message in Git?

1.  To indicate what has changed in a commit.

2.  To store the changes in a local Git repository.

3.  To push the changes to a remote Git repository.

4.  To see a full history of a the last 3 commits.

#### Answer 2:

1.  To indicate what has changed in a commit.

#### Question 3

Which of the following is not a valid format option for a Quarto document?

1.  Pdf.

2.  Html.

3.  Excel.

4.  Word.

#### Answer 3:

3.  Excel.

## Part 2

#### Question 1

1.  Paste the quiz directory into your home directory.

    I just extracted the files from the moodle. There is no need to explain any further.

2.  Next, create a new folder named ANS1.

    ``` bash
    mkdir ANS1
    ```

3.  Find and make a copy of `ShippingData.csv` file in the ANS1 folder.

    ``` bash
    cd ~/ADS_Q1/DATA

    cp ~/ADS_Q1/DATA/ShippingData.csv ~/ADS_Q1/ANS1/ShippingData.csv
    ```

4.  Rename the file to `Dataframe1.csv`.

    ``` bash
    cd ~/ADS_Q1/ANS1

    mv ShippingData.csv Dataframe1.csv
    ```

5.  Delete the Report directory.

``` bash
cd ..

rmdir Report
```

#### Question 2

1.  What command will select the first three columns from the file `Dataframe1.csv`?

``` bash
cd ~/ADS_Q1/ANS1

cut -d , -f 1-3 Dataframe1.csv
```

the cut command with 1-3 will show me columns 1-3 of Dataframe1.csv

2.  **Using code, What is the fifth item on the list? How much does it cost? Make your answer bold!**

Because the first line is the column names i use the head -n 6 on the Dataframe1.csv

``` bash
head -n 6 Dataframe1.csv
```

#### Question 3

1.  From `Dataframe1.csv`, What did the Costumers order more, `Bananas` or `Guitar`?

``` bash
grep -c Bananas Dataframe1.csv

grep -c Guitar Dataframe1.csv
```

The number of "Bananas" is 1484

The number of "Guitar" is 2913

The customers ordered more "Guitar"

2.  Print the contents of all of the lines containing the value `Microwave` in `Dataframe1.csv`.

``` bash
grep Microwave Dataframe1.csv
```

#### Question 4

1.  Create a new local git repository within the quiz directory.

    ``` bash
    cd ~/ADS_Q1

    git init
    ```

after init i get a message:

Initialized empty Git repository in C:/Users/daved/ADS_Q1/.git/

2.  Index and Commit all the files.

1.  Push all the files to a new directory in your GitHub Repository.

2.  Create a text link to your GitHub Repository.

Example:

[My Github Repository](https://github.com/Kaggle/learntools)

#### Question 5

1.Write a code so your friend can pull the repository to his computer.
